# Netlify configuration for Almeen Academy
# This file contains settings for building and deploying the site on Netlify.

[build]
  # This tells Netlify where the final website files are located.
  # For this project, they are in the root directory.
  publish = "/"

# The 'processing' settings tell Netlify to automatically optimize
# files during the build process. This improves performance without
# needing any complex plugins.
[build.processing]
  skip_processing = false

  [build.processing.css]
    bundle = true
    minify = true

  [build.processing.js]
    bundle = true
    minify = true

  [build.processing.html]
    pretty_urls = true

  # This will automatically compress all images in the project.
  # 'quality = 85' provides a good balance between file size and visual quality.
  [build.processing.images]
    compress = true
    quality = 85

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Images_almeen/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"



[build.environment]
  NODE_VERSION = "16"

# Enable Brotli compression
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 