backend:
  name: git-gateway
  branch: main  # yaha aapka default branch ka naam daalein, jaise main ya master

media_folder: "static/images/uploads"  # images ke liye folder
public_folder: "/images/uploads"

collections:
  - name: "principalMessage"
    label: "Principal's Message"
    files:
      - file: "content/principal-message.md"
        label: "Principal's Message Content"
        name: "principal_message"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
